name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole \
            --add-data "Untitled17.ipynb;." \
            --collect-all voila --collect-all nbformat --collect-all jinja2 \
            --hidden-import markupsafe --hidden-import nbclient --hidden-import traitlets \
            --hidden-import jupyter_client --hidden-import tornado --hidden-import pygments \
            main.py

      - name: List dist folder (debug)
        run: dir dist || echo "dist folder not found"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: osmoz-windows-exe
          path: dist/*.exe
          if-no-files-found: error

      - name: Create Release (attach exe when pushed with tag v*)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                - name: Build EXE with PyInstaller (single-line)
        run: pyinstaller --clean --log-level=DEBUG --onefile --noconsole --add-data "Untitled17.ipynb;." --collect-all voila --collect-all nbformat --collect-all jinja2 --hidden-import markupsafe --hidden-import nbclient --hidden-import traitlets --hidden-import jupyter_client --hidden-import tornado --hidden-import pygments main.py

