name: Build Windows EXE

on:
  workflow_dispatch:        # lancez-le à la main depuis l’onglet Actions
  push:
    tags: ["v*"]            # lance aussi sur un tag (ex: v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: >
          pyinstaller --onefile --noconsole
          --add-data "Osmoz_1_16.ipynb;."
          --collect-all voila --collect-all nbformat --collect-all jinja2
          --hidden-import markupsafe --hidden-import nbclient --hidden-import traitlets
          --hidden-import jupyter_client --hidden-import tornado --hidden-import pygments
          main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: osmoz-windows-exe
          path: dist/main.exe
          if-no-files-found: error

      # Optionnel: attacher à une Release quand on pousse un tag v*
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
